spring:
  redis:
    host: 127.0.0.1
    port: 32774
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 500

  datasource:
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:32778/vegetable-spring-jwt-admin?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root

  aop:
    auto: true

mybatis-plus:
  type-aliases-package: com.github.liuzhuoming23.vegetable.admin.*.domain
  mapper-locations: classpath:mapper/*/*.xml

#自定义配置参数
v-sja:
  #无需token验证的uri，多个用','分隔
  anonUrl: /login/**
  #日志保存敏感字段，会被在日志内统一替换为'******'。只适用于基本类型参数，不适用于实体类里的参数
  sensitiveField: password,newPassword,idcard
  #日志记录自定义级别，大于等于这个级别的才会被记录。默认值为0，即全部保存
  logLevel:
